### PR TITLE
Add working code to README

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by mkeasling** [comment]
👍  This would be a great addition!

**Comment by benwaffle** [comment]
@gwkunze can you merge this?

**Comment by gwkunze** [comment]
Apologies

**Comment by benwaffle** [comment]
otherwise i can just close it

**Comment by gwkunze** [comment]
whoops, I mean to write apologies and merge it, somehow the second part got forgotten.

**Comment by benwaffle** [comment]
no problem, thanks

**Pull request merged**
